### ISSUE TITLE
Gem fails to run if Rspec is not installed.

### ISSUE THREAD

**Issue by carlosplusplus** [loganhasson/aspen#2]
After running _gem install aspen_ on one of my computers, my computer did not recognize the _rspec --init_ command. You may want to check to ensure that _rspec_ is installed on the target PC prior to running your creation sequence.

**Comment by loganhasson** [comment]
Hmm, weird. It should be installing RSpec, as it's listed as a runtime dependency in the gemspec file. Is there a preferred way to handle ensuring dependencies are installed?

**Comment by mecampbellsoup** [comment]
Logan did you say you figured this one out? Do share if so :)

**Comment by carlosplusplus** [comment]
@loganhasson - you are absolutely right. It choked for some reason on one computer, but a simple _gem uninstall rspec_ and a fresh _gem install aspen_ did the trick. Tried it on both of mine just to be sure.

Closing this issue, as it is no longer relevant.
Apologies for the false alarm!
